/**
 *
 * @author juab
 */
public class IGUVentas extends javax.swing.JFrame {

    /**
     * Creates new form IGUVentas
     */
    public IGUVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        bottonagregar = new javax.swing.JMenu();
        bottoneliminar = new javax.swing.JMenu();
        bottonBuscar = new javax.swing.JMenu();
        bottonlistar = new javax.swing.JMenu();
        bottonregresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenuBar1.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N

        bottonagregar.setText("AGREGAR");
        bottonagregar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                bottonagregarComponentShown(evt);
            }
        });
        bottonagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonagregarActionPerformed(evt);
            }
        });
        jMenuBar1.add(bottonagregar);

        bottoneliminar.setText("ELIMINAR");
        jMenuBar1.add(bottoneliminar);

        bottonBuscar.setText("BUSCAR");
        jMenuBar1.add(bottonBuscar);

        bottonlistar.setText("LISTAR");
        jMenuBar1.add(bottonlistar);

        bottonregresar.setText("REGRESAR");
        jMenuBar1.add(bottonregresar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void bottonagregarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        // Limpiar el panel
        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.revalidate();

        // Crear componentes que quieras agregar
        javax.swing.JLabel labelNombre = new javax.swing.JLabel("Nombre:");
        javax.swing.JTextField textFieldNombre = new javax.swing.JTextField(20);
        javax.swing.JButton botonGuardar = new javax.swing.JButton("Guardar");

        // Agregar los componentes al panel
        

        // Actualizar el panel para que se muestren los nuevos componentes
        jPanel1.repaint();
        jPanel1.revalidate();

        
    }                                             

                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IGUVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IGUVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IGUVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IGUVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IGUVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu bottonBuscar;
    private javax.swing.JMenu bottonagregar;
    private javax.swing.JMenu bottoneliminar;
    private javax.swing.JMenu bottonlistar;
    private javax.swing.JMenu bottonregresar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}